### ISSUE TITLE
Cooperate - Administracion Menu - Archivo HTML

### ISSUE THREAD

**Issue by edgar1090** [almacs/Cooperate#3]
Administracion - Menu - Nuevo - Archivo Local HTML

Al dar de alta un archivo local HTML de un formulario basico permite guardarlo pero al consultarlo marca error.
(favor de especificar si es la forma correcta en la que se realizo la prueba)

![image](https://cloud.githubusercontent.com/assets/11621492/7278929/0c061f1c-e8de-11e4-962e-e785b6f1ecb7.png)

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Escenario exitoso

![image](https://cloud.githubusercontent.com/assets/11621492/7306230/4bdab83c-e9c9-11e4-9dd9-ff8178c0a4fa.png)
