### ISSUE TITLE
Cooperate - Administracion Menu - Flujo

### ISSUE THREAD

**Issue by edgar1090** [almacs/Cooperate#4]
Administracion - Menu - Nuevo - Flujo

No permite seleccionar un flujo del listado de flujos

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Escenario Exitoso

![image](https://cloud.githubusercontent.com/assets/11621492/7306261/87978846-e9c9-11e4-870a-d4c1ca788f12.png)
