### ISSUE TITLE
Cooperate - Administracion Menu - Recurso interno del sistema

### ISSUE THREAD

**Issue by edgar1090** [almacs/Cooperate#5]
Administracion - Menu - Nuevo - Recurso interno del sistema

No permite seleccionar un flujo de trabajo del lista del flujos

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Escenario Exitoso

![image](https://cloud.githubusercontent.com/assets/11621492/7306288/d7af18a8-e9c9-11e4-8523-152f2896b013.png)
