### ISSUE TITLE
Cooperate - Administracion Menu - Forma autoadministrativa

### ISSUE THREAD

**Issue by edgar1090** [almacs/Cooperate#6]
Administracion - Menu - Nuevo - Forma autoadministrativa
1. Dar de alta forma autoadministrativa sin la opcion de Exportar y Nuevo
2. Consultar un registro de la forma dada de alta
3. Clic en cancelar

Se visualizara que ya permite exportar y crear un nuevo registro aun cuando no deberia

**Comment by mtrejo30** [comment]
Validar

**Comment by edgar1090** [comment]
Escenario Exitoso
